name: Deploy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Install MTA Build tool
        run: npm install -g mbt

      - name: Install dependency
        run: npm install

      - name: Build MTA
        run: mbt build -p cf -t mta_archives --mtar mta.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mta
          path: ./mta_archives/mta.tar
